import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Pretendard = localFont({
  src: '../../../packages/sdu-kit/assets/font/PretendardVariable.woff2',
  display: 'swap',
  weight: '400 500 700',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Pretendard.className}>
        {children}
      </body>
    </html>
  );
}
